<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GSO Reports &amp; Analytics</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color: #111827; font-size: 12px; }
        h1, h2 { color: #047857; margin-bottom: 8px; }
        .meta { margin-bottom: 16px; }
        .meta span { display: inline-block; margin-right: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #d1d5db; padding: 6px 8px; text-align: left; }
        th { background-color: #ecfdf5; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-weight: bold; }
        .badge.approved { background-color: #d1fae5; color: #047857; }
        .badge.rejected { background-color: #fee2e2; color: #b91c1c; }
        .summary-grid { display: flex; gap: 12px; margin-bottom: 16px; }
        .summary-card { flex: 1; border: 1px solid #d1d5db; border-radius: 6px; padding: 10px; background-color: #fafafa; }
        .breakdown-table { margin-top: 16px; }
        footer { margin-top: 24px; font-size: 10px; color: #6b7280; text-align: right; }
    </style>
</head>
<body>
    <h1>GSO Reports &amp; Analytics</h1>
    <div class="meta">
        <span><strong>Generated:</strong> {{ $generatedAt->format('Y-m-d H:i') }}</span>
        @if($rangeStart || $rangeEnd)
            <span><strong>Date Range:</strong> {{ optional($rangeStart)->format('Y-m-d') ?? 'N/A' }} - {{ optional($rangeEnd)->format('Y-m-d') ?? 'N/A' }}</span>
        @endif
    </div>

    <div class="summary-grid">
        <div class="summary-card">
            <strong>Total Approved</strong>
            <div>{{ $stats['totalApproved'] }}</div>
        </div>
        <div class="summary-card">
            <strong>Total Rejected</strong>
            <div>{{ $stats['totalRejected'] }}</div>
        </div>
        <div class="summary-card">
            <strong>Approval Rate</strong>
            <div>{{ $stats['approvalRate'] }}%</div>
        </div>
        <div class="summary-card">
            <strong>Avg. Response Time</strong>
            <div>{{ $stats['avgResponseTime'] }} hrs</div>
        </div>
    </div>

    @if(!empty($breakdown))
        <h2>Request Type Breakdown</h2>
        <table class="breakdown-table">
            <thead>
                <tr>
                    <th>Request Type</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($breakdown as $item)
                    <tr>
                        <td>{{ $item['type'] }}</td>
                        <td>{{ $item['count'] }}</td>
                        <td>{{ $item['percentage'] }}%</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <h2>Approval Records</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Ticket ID</th>
                <th>Event</th>
                <th>Organization</th>
                <th>Request Type</th>
                <th>Decision</th>
                <th>Response Time (hrs)</th>
                <th>Comments</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $record)
                <tr>
                    <td>{{ $record['date'] }}</td>
                    <td>{{ $record['ticketId'] }}</td>
                    <td>{{ $record['eventName'] }}</td>
                    <td>{{ $record['organization'] }}</td>
                    <td>{{ $record['requestType'] }}</td>
                    <td>
                        <span class="badge {{ strtolower($record['decision']) }}">
                            {{ $record['decision'] }}
                        </span>
                    </td>
                    <td>{{ $record['responseTime'] }}</td>
                    <td>{{ $record['comments'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8">No records available for the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <footer>Generated by Org Events Scheduling System</footer>
</body>
</html>
